ARDUINO_DIR = /Applications/Arduino.app/Contents/Java

TARGET       			= clock_controller
MCU          			= atmega168
F_CPU        			= 16000000
AVRDUDE_ARD_PROGRAMMER 	= avrispmkii
ARD_PORT 				= usb

# Separate by spaces
ARDUINO_LIBS = SoftwareSerial Wire

include /Users/rob/Documents/AVR/Makefile.arduino
